name: serialization
version: 0.11.0
author: Alan Knight <alanknight@google.com>
description: Provide a serialization facility for Dart objects.
homepage: https://github.com/google/serialization.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  analyzer: '>=0.21.1 <0.24.0'
  barback: '>=0.13.0 <0.16.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.12.0'
transformers:
- serialization :
    files:
    - test/transformer/test_models.dart
    rules_file_name: 'test_models_serialization_rules.dart'
    $include: ["test/transformer/test_models.dart", "test/transformer/transformer_test.dart"]
- serialization :
    files:
    - test/transformer/test_models_for_maps.dart
    format: 'maps'
    rules_file_name: 'test_models_for_maps_serialization_rules.dart'
    $include: ["test/transformer/test_models_for_map.dart", "test/transformer/transformer_maps_test.dart"]
- serialization :
    use_annotation: true
    rules_file_name: 'test_models_for_annotation_serialization_rules.dart'
    $include: ["test/transformer/test_models_for_annotation.dart", "test/transformer/transformer_annotation_test.dart"]
