name: serialization
version: 0.11.0
author: Alan Knight <alanknight@google.com>
description: Provide a serialization facility for Dart objects.
homepage: https://github.com/google/serialization.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  analyzer: '>=0.21.1 <0.24.0'
  barback: '>=0.13.0 <0.16.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.12.0'
transformers:
  - serialization :
      $include: ["test/transformer/test_models.dart"]
  - serialization :
      $include: ["test/transformer/test_models_for_maps.dart"]
      format: "maps"
